In [23]:
from azure.storage.blob import *
import pandas as pd
import io
import os

print(os.getcwd())
data = pd.read_csv("data/train_dataset.csv")
data

c:\Users\jcharley\Documents\VSC\Azure_ML_services\Azure_ML_Services\Storage\fromcsv_to_blob

,Unnamed: 0,Access_Level,Training_Completed,Code_postal,Email_Domain,EmployeeTargeted,Gender,Social_Media,behaviorPattern2,peerUsageMetric6,usageMetric2,usageMetric5,fraudTraining
0,3402,4,1.0,10000,slideshare.net,1.0,0,2.0,1,6,0,4,1
1,2817,2,1.0,84995,slideshare.net,0.0,0,1.0,0,5,1,6,1
2,3692,2,1.0,10000,ox.ac.uk,1.0,0,0.0,0,0,0,4,1
3,4229,3,0.0,24999,si.edu,1.0,1,0.0,2,6,0,6,0
4,11179,2,1.0,24999,si.edu,1.0,1,1.0,2,3,1,5,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10495,10005,5,1.0,24999,ox.ac.uk,1.0,1,0.0,1,5,3,5,0
10496,9789,1,1.0,10000,si.edu,1.0,1,1.0,0,2,0,3,0
10497,6652,1,0.0,24999,si.edu,1.0,1,1.0,0,5,1,2,0
10498,5414,3,0.0,24999,slideshare.net,1.0,0,2.0,0,6,1,3,1
10499,3163,1,0.0,24999,si.edu,1.0,1,2.0,0,4,0,2,1

In [33]:
from azure.storage.blob import ContainerClient

container_client = ContainerClient(account_url='........./containertraining/train_dataset.csv', # note this is the url and not name
                                   container_name="containertraining",
                                   credential='.........4L+P6ScNoGtt/211bag==')

blob_names = container_client.list_blobs()
print(blob_names)

<iterator object azure.core.paging.ItemPaged at 0x29613351100>